[package]
name = "srt-c-unittests"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
srt-c = {path = "../srt-c"}

[build-dependencies]
cc = "1"