language: rust
sudo: false

os:
  - osx
  - linux

rust:
  - stable
  - beta
  - nightly

cache: cargo

script:
  - cargo build --verbose
  - RUST_LOG=srt=info,lossy=info,message_splitting=info cargo test --verbose

